#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  2 18:09:18 2017

Still incomplete at the moment. Does not work for 1 element finding 1, i.e input both '3' and '1' prints wrong behaviour.
Would require to implement in separate try and exception.

@author: jameselijah
"""
user_list = list(input('Input list of numbers(integers) separated by spaces:'))
while len(user_list) <= 0: #error check in case user input null
    print ('please enter a list filled with integers only' )
    user_list = list(input('Input list of numbers(integers) separated by spaces:'))
user_int = int(input('Input the integer you want to count in the list you gave:'))

while len(user_list) == 1:
    if user_int == user_list[0]:
        print ('Your integer %d appeared once in your list once!'%user_int)
        break
    else:
        print ('Your integer is not in the list')
        break

else:
    def counting_sort(user_list):# function to output an input of user and to sort it
        n = len(user_list)
        for i in range(1,n):
            temp = user_list[i]
            x = i 
            while x > 0 and user_list[x-1]> temp: #To create a mechanic to arrange to smallest to biggest
                user_list[x] = user_list[x-1]
                x = x -1 # to go back to the left to produce my list
            user_list[x] = temp #put back the other value 
    print (user_list)
    
    print('Your generated list is shown as:',end='')
    counting_sort(user_list)
    
    def counter(counting_sort):#created a new function to count for the list element in the input method of the user
        occurence = {}
        for i in user_list:
            if i in occurence:
                occurence[i] = occurence[i] + 1
        else:
            occurence[i] = 1
            return occurence
        
        print ('The number of times your integer appeared in your list is:' )
        print(counter(counting_sort))

