#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  2 18:09:18 2017

Still incomplete at the moment. Does not work for 1 element finding 1, i.e input both '3' and '1' prints wrong behaviour.
Would require to implement in separate try and exception.

@author: jameselijah
"""

import time
try:
    
    gather_entries()
    
    def gather_entries():
        global user_list
        global user_int
        
        user_entry = input('Input list of numbers(integers) separated by spaces:')
        
        user_list = user_entry.split()
        
        for i in range(len(user_list)):
            int(user_list[i])
            
        user_int = int(input('Input the integer you want to count in the list you gave:'))
        
        if len(user_list) == 1:
            if user_int == user_entry[0]:
                print ('Your integer %d appeared once in your list once!'%user_int)
                playagain()
            else:
                print ('Your integer is not in the list')
                print ("")
                playagain()
                
        
        print('Your generated list is shown as:',end='')
        print (user_list)
        
        counter(user_list)
    
    def counter(_list):#created a new function to count for the list element in the input method of the user
        global user_list
        global user_int
        global occurences
        
        occurences = 0
        
        for i in range(len(_list)):
            if user_list[i] == user_int:
                occurences = occurences + 1
            else:
                pass

            
        print ('The number of times your integer appeared in your list is: %d' % (occurences))
        playagain()
        
    
    def playagain():
        choice = input("Play again? Yes or No:").upper()
        
        if choice == "YES" or choice == "Y":
            gather_entries()
            
        elif choice == "NO" or choice == "N":
            print ("Thank you for playing")
        else:
            print ("Unknown command. Try Again")
            print ("")
            playagain()
            
    
except ValueError:
    print ("Pls enter valid values (integers or floats)!")
    time.sleep(0.5)
    print ("Kernel restarting")
    time.sleep(0.5)
    print (".")
    time.sleep(0.5)
    print (".")
    gather_entries()